spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esquela
    username: postgres
    password: edstem@23
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: student-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sharok.esquela.contract
    topic:
      student: student-events
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
